version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile_php_apache
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./:/var/www/html
    tty:
      true
    env_file:
      - .env

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    env_file:
      - .env
